apps/chat/urls.py
from django.urls import path
from .views import * 


app_name = 'chat'

chat_list = ChatView.as_view({
    'post' : 'create',
    'get' : 'list'
})

chat_detail = ChatView.as_view({
    'get': 'retrieve',
    'put'   : 'update',
    'delete': 'destroy'
})




urlpatterns = [
    path('chat', PageChatView.as_view(), name='page_chat'),
    path('contact/<int:pk_c>/chats', chat_list , name='chats'),
    path('contact/<int:pk_c>/chats/<int:pk>', chat_list , name='chats')
]

apps/user/urls.py
from django.urls import path
from .views import LoginView ,UserView ,LogoutView

app_name = 'user'
urlpatterns = [
    path('', LoginView.as_view(), name='login'), 
    path('logout', LogoutView.as_view(), name='logout'), 
    path('users', UserView.as_view())
]

settings/urls.py
from django.contrib import admin
from django.urls import path
from  admin import admin_site
from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    #url('myadmin/', admin_site.urls),
    url('', include('user.urls', namespace='users')),
    url('contact/', include('contact.urls', namespace='contact')),
    url('message/', include('message.urls', namespace='message')),
    url('',include('chat.urls', namespace='chat')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/chat/models.py
from django.db import models
from typechat.models import TypeChat
from contact.models import Contact

class Chat(models.Model):
    name = models.CharField(verbose_name='Nombre',max_length=50)
    avatar = models.ImageField(verbose_name='avatar', null=True, blank=True)
    date_registration =  models.DateTimeField(auto_now_add=True , verbose_name=u'Fecha de Registro')
    type_chat = models.ForeignKey( TypeChat , on_delete=models.SET_NULL, null=True, verbose_name='Tipo Chat' )
    participants = models.ManyToManyField(Contact, related_name='chat', blank=True , verbose_name='Participantes')
   
    def __str__(self):
        return self.name

apps/chat/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from django.views.generic import FormView,TemplateView
from rest_framework import viewsets

from contact.models import Contact
from .serializers import ChatSerializer
from .models import Chat
import json


class PageChatView(APIView):
    def get (self,request):
        user_contact =  Contact.objects.get(user=request.user.pk)        
        chat = Chat.objects.filter(participants__id=user_contact.id).order_by('-id')[:1]
        serializer = (ChatSerializer(chat,many=True).data[0])
          
        chat_obj = {
            "id": serializer['id']
        }
        if(serializer['type_chat'] == 2):
            chat_obj['name'] = serializer['name']
            chat_obj['avatar'] = serializer['avatar']
        else:
            for data in serializer['participants']:
                if data['id'] != user_contact.id: 
                    chat_obj['name'] = data['user']['username']
                    chat_obj['avatar'] = data['user']['avatar']

        return render(request, 'chat.html' , { 'user' : request.user , "user_contact" : user_contact , 'chat': chat_obj } )

class ChatView(viewsets.ModelViewSet):
    permission_classes = ()
    serializer_class = ChatSerializer 
    queryset = Chat.objects.all()

    def get_queryset(self):
        queryset = self.queryset.filter(participants__id=self.kwargs['pk_c']).order_by('-id')
        return queryset
      

templates/chat-copia.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Chat</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>    
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        
    
    
    </head>
	<!--Coded With Love By Mutiullah Samim-->
	<body>
		<div class="container-fluid h-100">
			<div class="row justify-content-center h-100">
				<div class="col-md-4 col-xl-3 chat">					
					<div class="card mb-sm-3 mb-md-0 contacts_card">					
						<div class="card-header">
							<div class="card-header msg_head">
								<div class="d-flex bd-highlight">
									<div class="img_cont_msg">
										<img src=" media/{{ user.avatar }}" class="rounded-circle user_img_msg">
									</div>
									<div class="user_info">
										<span id="chat-user" data-contact="{{ user_contact.pk }}" >{{ user.username }}</span>
									</div>
								</div>
							</div>

							<div class="input-group">							
								<input type="text" placeholder="Search..." name="" class="form-control search">
								<div class="input-group-prepend">
									<span class="input-group-text search_btn"><i class="fas fa-search"></i></span>
								</div>
							</div>						
						</div>
						<div class="card-body contacts_body">
							<ui class="contacts" id="contacts">
							<!--
								<li class="active">
									<div class="d-flex bd-highlight">
										<div class="img_cont">
											<img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img">
											<span class="online_icon"></span>
										</div>
										<div class="user_info">
											<span>Khalid</span>
											<p>Kalid is online</p>
										</div>
									</div>
								</li>
								<li>
									<div class="d-flex bd-highlight">
										<div class="img_cont">
											<img src="https://2.bp.blogspot.com/-8ytYF7cfPkQ/WkPe1-rtrcI/AAAAAAAAGqU/FGfTDVgkcIwmOTtjLka51vineFBExJuSACLcBGAs/s320/31.jpg" class="rounded-circle user_img">
											<span class="online_icon offline"></span>
										</div>
										<div class="user_info">
											<span>Taherah Big</span>
											<p>Taherah left 7 mins ago</p>
										</div>
									</div>
								</li>
								<li>
									<div class="d-flex bd-highlight">
										<div class="img_cont">
											<img src="https://i.pinimg.com/originals/ac/b9/90/acb990190ca1ddbb9b20db303375bb58.jpg" class="rounded-circle user_img">
											<span class="online_icon"></span>
										</div>
										<div class="user_info">
											<span>Sami Rafi</span>
											<p>Sami is online</p>
										</div>
									</div>
								</li>
							-->		
							</ui>
						</div>
						<div class="card-footer"></div>
					</div>
				</div>

				<div class="col-md-8 col-xl-6 chat" id="card-section">
					<div class="card">						
						<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<div class="img_cont">
									<img src="{{chat.avatar}}" class="rounded-circle user_img" id="img-chat">
									<span class="online_icon"></span>
								</div>
								<div class="user_info">
									<span id='name-chat' data-chatws="{{chat.id}}" >{{chat.name}}</span>
									<p>1767 Messages</p>
								</div>
								<div class="video_cam">
									<span><i class="fas fa-video"></i></span>
									<span><i class="fas fa-phone"></i></span>
								</div>
							</div>
							<span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
							<div class="action_menu">
								<ul>
									<li><i class="fas fa-user-circle"></i> View profile</li>
									<li><i class="fas fa-users"></i> Add to close friends</li>
									<li><i class="fas fa-plus"></i> Add to group</li>
									<li><i class="fas fa-ban"></i> Block</li>
								</ul>
							</div>
                        </div>
                        
						<div class="card-body msg_card_body" id="msg-card-body">
							<!--
							<div class="d-flex justify-content-start mb-4">
								<div class="img_cont_msg">
									<img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img_msg">
								</div>
								<div class="msg_cotainer">
									Hi, how are you samim?
									<span class="msg_time">8:40 AM, Today</span>
								</div>
							</div>
							<div class="d-flex justify-content-end mb-4">
								<div class="msg_cotainer_send">
									Hi Khalid i am good tnx how about you?
									<span class="msg_time_send">8:55 AM, Today</span>
								</div>
								<div class="img_cont_msg">
									<img src="https://i.pinimg.com/564x/a6/58/32/a65832155622ac173337874f02b218fb.jpg" class="rounded-circle user_img_msg">
								</div>
							</div>
							-->
						</div>
						<div class="card-footer"  id="card-footer">
							<div class="input-group">
								<div class="input-group-append">
									<span class="input-group-text attach_btn" ><i class="fas fa-paperclip"></i></span>
								</div>

								<textarea id="message-send" name="" class="form-control type_msg" placeholder="Type your message..."></textarea>
								<div class="input-group-append" id="chat-message-submit">
									<span class="input-group-text send_btn" ><i class="fas fa-location-arrow"></i></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
	
	<script  src="{% static 'js/main.js' %}"></script>
	<script type="module" src="{% static 'js/app.js' %}"></script>

</html>

templates/chat.html
{% extends 'index.html' %}
{% load static %}

{%block header %}
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{%endblock%}


{%block navar %}

{%endblock%}



{%block content %}
<div class="container-fluid h-100">
	<div class="row justify-content-center h-100">
		<div class="col-md-4 col-xl-3 chat">
			<div class="card mb-sm-3 mb-md-0 contacts_card">
				<div class="card-header">
					<div class="card-header msg_head">
						<div class="d-flex bd-highlight">
							<div class="img_cont_msg ">
								<img src=" media/{{ user.avatar }}" class="rounded-circle user_img_msg">
							</div>
							<div class="user_info ">
								<span id="chat-user" class="color_p"
									data-contact="{{ user_contact.pk }}">{{ user.username }}</span>
							</div>
							<span id="action_menu_btn_contact" class="color_p action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
							<div class="action_menu" id="action_menu_contact">
								<ul>
									<li><i class="fas fas fa-plus"></i>Nuevo Grupo</li>
									<li><i class="fas fa-user-circle"></i> Perfil</li>
									<li><i class="fas fa-sign-out-alt"></i><a href="{% url 'user:logout' %}"> Logout </a></a></li>	
											
								</ul>
							</div>
						</div>
					</div>
					<div class="input-group">
						<input type="text" placeholder="Search..." name="" class="form-control search">
						<div class="input-group-prepend">
							<span class="input-group-text search_btn"><i class="fas fa-search"></i></span>
						</div>
					</div>
				</div>
				<div class="card-body contacts_body">
					<ui class="contacts" id="contacts"></ui>
				</div>
				<div class="card-footer"></div>
			</div>
		</div>

		<div class="col-md-8 col-xl-9 chat" id="card-section">
			<div class="card">
				<div class="card-header msg_head">
					<div class="d-flex bd-highlight">
						<div class="img_cont">
							<img src="{{chat.avatar}}" class="rounded-circle user_img" id="img-chat">
							<span class="online_icon"></span>
						</div>
						<div class="user_info">
							<span id='name-chat' class="color_p" data-chatws="{{chat.id}}">{{chat.name}}</span>
							<p>1767 Messages</p>
						</div>
						<div class="video_cam">
							<span><i class="fas fa-video"></i></span>
							<span><i class="fas fa-phone"></i></span>
						</div>
								<ul>
						<span id="action_menu_btn" class="color_p action_menu_btn "><i class="fas fa-ellipsis-v"></i></span>
						<div class="action_menu" id="action_menu">
							<ul>
								<li><i class="fas fa-user-circle"></i> View profile</li>
								<li><i class="fas fa-users"></i> Add to close friends</li>
								<li><i class="fas fa-plus"></i> Add to group</li>
								<li><i class="fas fa-ban"></i> Block</li>
							</ul>
						</div>
					</div>
				</div>

				<div class="card-body msg_card_body" id="msg-card-body"></div>
				<div class="card-footer" id="card-footer">
					<div class="input-group">
						<div class="input-group-append">
							<span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
						</div>

						<textarea id="message-send" name="" class="form-control type_msg"
							placeholder="Type your message..."></textarea>
						<div class="input-group-append" id="chat-message-submit">
							<span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}


{%block script %}
<script type="module" src="{% static 'js/app.js' %}"></script>
{%endblock%}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>    
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    {%block header %}

    {%endblock%}
 

    <title>CHATGO!</title>
</head>
<body>
    {%block navar %}

    {%endblock%}
    {%block content %}

    {%endblock%}
	<script  src="{% static 'js/main.js' %}"></script>
    
    
    {%block script %}   
    {%endblock%}

</html>
</body>
</html>

templates/login-copia.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="images/img-01.png" alt="IMG">
				</div>

				<form class="login100-form validate-form">
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="#">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	
<!--===============================================================================================-->	
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>

templates/login.html
{% extends 'index.html' %}
{% load static %}
{%block header %}

<link rel="stylesheet" href="{% static 'css/style.css' %}" />    

{%endblock%}

{%block content %}
<div class="container-fluid h-100">
	<div class="row h-100 justify-content-center ">
		<div class="col-sm-6 col-md-6 col-xl-6 container_img"></div>

		<div class="col-sm-6 col-md-6 col-xl-6 d-flex align-items-center justify-content-center" >
			<div class="login d-flex  flex-column  justify-content-between">
				 <!-- Icon -->
				<div class="card-header-login msg_head p-4">
					<h1 class="text-center title_p">ChatGo!</h1>					
				 </div>	
				<p class="text-center text_p m-4 ">Bienvenido, no hay nada mejor que estar conectado.</p>	  
				
				<form class="h-75 d-flex flex-column align-items-center" method="post">
					{% csrf_token %}
					{% if form.errors %}
						{% for field_with_error,error_messages in form.errors.items %}
							<div class="alert alert-danger form-group errors"> {{error_messages }}</div>
						{% endfor %}
					{% endif %}
					
								
					
					<div class="form-group form_input ">
					 <!-- <label for="exampleInputEmail1">Email address</label> 
					  <input type="email" class="form-control" id="email" placeholder="Email" required> -->
					  {{ form.email }}
					</div>
					<div class="form-group form_input">
					 
					 <!--   <input type="password" class="form-control" id="password" placeholder="Password" required> -->
					  {{ form.password }}
					</div>
					<div class="form_btn mt-3 mb-2">
						<button type="submit" class="btn btn_login">Log In</button>
					</div>
					
				</form>
				
				<!-- Remind Passowrd -->
				<div class="card-footer-login text-center text_p login_footer mt-5">
					<a class="underlineHover " href="#">Forgot Password?</a>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}  